### ISSUE TITLE
Group commits by prefix

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-tools/releaseman#11]
E.g. group `FIX:`, `BREAKING:` and `NEW:` prefixed git commits. Instead of a single flat list of commits this could be used to auto generate categorized commit lists, like:

```
## Breaking Changes

- ....
- ....

## New Features

- ...
- ....

## Bug Fixes

- ....
- ....
````

**Comment by lpusok** [comment]
Closing as repo deprecated.
