### ISSUE TITLE
add a `show` command - releaseman show RELEASE.VERSION.NUMBER should print that version's changelog

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-tools/releaseman#13]
Useful to be used from other tools mainly, but of course might be useful for local use too.

I'd say it could work similar to `git show`, which if there's no param passed shows the last commit, and if you pass a commit hash shows that commit. Similarly `releaseman show` could show the latest version's changelog section by default, and if a version is specified show that section.

**Comment by lpusok** [comment]
Closing as repo deprecated.
